# Generated by Django 3.1.2 on 2020-10-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(max_length=5000, verbose_name='Description')),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
    ]
